#!/bin/bash


function cinder_volume_install() {
yum --enablerepo=centos-openstack-stein,epel -y install openstack-cinder python2-crypto targetcli
mv /etc/cinder/cinder.conf /etc/cinder/cinder.conf.org
cat > /etc/cinder/cinder.conf << EOF
# create new
[DEFAULT]
# define own IP address
my_ip = 172.170.75.13
log_dir = /var/log/cinder
state_path = /var/lib/cinder
auth_strategy = keystone
# RabbitMQ connection info
transport_url = rabbit://openstack:huawei@172.170.75.11
# Glance connection info
glance_api_servers = http://172.170.75.11:9292
enable_v3_api = True

# MariaDB connection info
[database]
connection = mysql+pymysql://cinder:huawei@172.170.75.11/cinder

# Keystone auth info
[keystone_authtoken]
www_authenticate_uri = http://172.170.75.11:5000
auth_url = http://172.170.75.11:5000
memcached_servers = 172.170.75.11:11211
auth_type = password
project_domain_name = default
user_domain_name = default
project_name = service
username = cinder
password = huawei

[oslo_concurrency]
lock_path = \$state_path/tmp
EOF
chmod 640 /etc/cinder/cinder.conf
chgrp cinder /etc/cinder/cinder.conf
systemctl start openstack-cinder-volume
systemctl enable openstack-cinder-volume
}

cinder_volume_install
