#!/usr/bin/bash

function create_pools() {
ceph osd pool create volumes 32
ceph osd pool create images 32
ceph osd pool create vms 32
ceph osd pool create backups 32
}

function setup_client_authen() {
ceph auth get-or-create client.cinder mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool=volumes, allow rwx pool=vms, allow rx pool=images'
ceph auth get-or-create client.glance mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool=images'
ceph auth get-or-create client.cinder-backup mon 'profile rbd' osd 'profile rbd pool=backups'
ceph auth get-or-create client.glance | ssh ostack1 tee /etc/ceph/ceph.client.glance.keyring
ssh ostack1 chown glance:glance /etc/ceph/ceph.client.glance.keyring
ceph auth get-or-create client.cinder | ssh ostack2 tee /etc/ceph/ceph.client.cinder.keyring
ssh ostack2 chown cinder:cinder /etc/ceph/ceph.client.cinder.keyring
ceph auth get-or-create client.cinder-backup | ssh ostack2 tee /etc/ceph/ceph.client.cinder-backup.keyring
ssh ostack2 chown cinder:cinder /etc/ceph/ceph.client.cinder-backup.keyring
ceph auth get-key client.cinder | ssh ostack2 tee client.cinder.key
}
setup_client_authen
