#!/usr/bin/bash

# on the nova-compute, cinder-backup and cinder-volume node, use both the Python bindings adn the client command line tools:
#yum install ceph-common -y
#yum install python-rbd -y

# onthe compute nodes, add the secret key to libvirt and remove the temporary copy of the key:
UUID=$(uuidgen)

cat > secret.xml <<EOF
<secret ephemeral='no' private='no'>
  <uuid>${UUID}</uuid>
  <usage type='ceph'>
    <name>client.cinder secret</name>
  </usage>
</secret>
EOF
virsh secret-define -file secret.xml
virsh secret-set-value --secret ${UUID} --base64 $(cat client.cinder.key) && rm client.cinder.key secret.xml
